#!/usr/bin/env node
/**
 * @description VPS cron harness — Reaper COMPOSITION ROOT (task-9 glue-3). ONE shared cron for
 * the WHOLE VPS: a crontab invokes this file once (`node core/vps/run-reaper.mjs --config
 * <fleet.json>`), and it reads a config carrying every project to sweep, then WIRES the real
 * seams — the `listWorktrees` producer (./list-worktrees.mjs) scoped over `config.projects`, the
 * run-lock release (./run-lock.mjs), the cron-state read-only attempt counter (./cron-state.mjs),
 * real tmux liveness/kill probes, and `git worktree remove` / `git branch -D` — around the
 * already-built LOGIC function reaper (./reaper.mjs, task-8).
 *
 * `runReaper(config, deps)` is the testable seam: `deps` DEFAULTS to the real wiring above but is
 * fully injectable so run-crons.test.mjs can pass a fake reaper + a fake listWorktrees producer
 * and assert the OBSERVABLE wiring — specifically that the zero-arg `listWorktrees` seam handed
 * to the reaper logic delegates to the injected producer over `config.projects`, never a real git
 * call from the test.
 *
 * @param {object} config
 * @param {string} config.project
 * @param {string} config.owner
 * @param {string} config.repo
 * @param {string} config.projectRoot
 * @param {string} config.stateDir
 * @param {string} config.worktreeRoot
 * @param {string} config.homeDir
 * @param {Array<{project: string, projectRoot: string, stateDir: string}>} [config.projects] -
 *   every project the shared reaper sweeps in one invocation.
 * @param {string} [config.defaultBranch] - default "main". Threaded into the workPreserved probes
 *   (branchMerged / inspectWorktree) so the completed sweep stays live on fleets whose default
 *   branch is not main. NOTE: install-crons.mjs's reconcileFleet does NOT populate defaultBranch
 *   today, so this is always undefined -> always "main" for a fleet config generated by the
 *   reconciler. It must be hand-added to reaper.json for a fleet whose default branch is not main;
 *   until then the completed sweep fails closed (never prunes) on such a project, because the
 *   branchMerged/inspectWorktree probes resolve "main" against a non-main default branch and return
 *   null (unknown) -> fail-closed.
 * @param {object} [deps] - Injectable seams; each defaults to the real wiring when omitted.
 * @param {(opts: object) => void} [deps.reaper] - default: real reaper from ./reaper.mjs
 * @param {(opts: object) => Array<object>} [deps.listWorktrees] - default: real listWorktrees from ./list-worktrees.mjs
 * @param {(projectRoot: string) => string} [deps.runGitWorktreeList] - default: real `git worktree list --porcelain`
 * @param {(opts: {stateDir: string}) => object|null} [deps.readHolder] - default: real readHolder from ./run-lock.mjs
 * @param {(args: string[]) => any} [deps.ghExec] - default: real `gh` CLI invocation
 * @param {object} [deps.runLock] - default: real { release } from ./run-lock.mjs
 * @param {object} [deps.counter] - default: real read-only { read } from ./cron-state.mjs
 * @param {(sessionId: string) => boolean} [deps.tmuxHasSession] - default: real `tmux has-session` probe
 * @param {(sessionId: string) => void} [deps.tmuxKillSession] - default: real `tmux kill-session`
 * @param {(issueNumber: number) => boolean} [deps.prExists] - default: real `gh pr list --head harness/<n>` check
 * @returns {void}
 */
import { spawnSync } from "node:child_process";
import { readdirSync } from "node:fs";
import { join } from "node:path";

import { loadConfig } from "./run-cron-a.mjs";
import { reaper } from "./reaper.mjs";
import { listWorktrees } from "./list-worktrees.mjs";
import { readHolder } from "./run-lock.mjs";
import { scopedGh, defaultGhExec } from "./gh-exec.mjs";
import * as counterModule from "./cron-state.mjs";
import * as runLockModule from "./run-lock.mjs";
import { makeNotifier, closeForumTopic as realCloseForumTopic } from "./notify-telegram.mjs";
import { readMeta as realReadMeta, updateMeta as realUpdateMeta } from "./obs-outbox.mjs";
import { pickSessionPr } from "./cron-a-exit.mjs";

/** @description Real `git -C <projectRoot> worktree list --porcelain` stdout. Fail-soft -> "". */
function defaultRunGitWorktreeList(projectRoot) {
  const res = spawnSync("git", ["-C", projectRoot, "worktree", "list", "--porcelain"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (res.error || res.status !== 0) return "";
  return res.stdout ?? "";
}

/** @description Real `tmux has-session -t <id>` liveness probe — true iff the session exists. */
function defaultTmuxHasSession(sessionId) {
  const res = spawnSync("tmux", ["has-session", "-t", sessionId], { stdio: "ignore" });
  return res.status === 0 && !res.error;
}

/** @description Real `tmux kill-session -t <id>`. Best-effort; failures swallowed. */
function defaultTmuxKillSession(sessionId) {
  try {
    spawnSync("tmux", ["kill-session", "-t", sessionId], { stdio: "ignore" });
  } catch {
    // best-effort watchdog kill
  }
}

/**
 * @description Default listObsRuns producer: sweeps every configured project's stateDir for
 * obs-<issue>.json files and returns { metaPath, meta } pairs (meta pre-read via the canonical
 * obs-outbox readMeta). reaper.mjs never touches fs directly — this is the composition-root wiring.
 * Fail-soft per project: an unreadable stateDir contributes no runs (the shared cron never aborts
 * every other project because one stateDir is unreadable).
 * @param {Array<{ project: string, projectRoot: string, stateDir: string }>} projects
 * @param {(metaPath: string) => object|null} readMetaFn
 * @returns {Array<{ metaPath: string, meta: object }>}
 */
function defaultListObsRuns(projects, readMetaFn) {
  const runs = [];
  for (const project of projects ?? []) {
    let files;
    try {
      files = readdirSync(project.stateDir);
    } catch {
      continue;
    }
    for (const file of files) {
      if (!file.startsWith("obs-") || !file.endsWith(".json")) continue;
      const metaPath = join(project.stateDir, file);
      const meta = readMetaFn(metaPath);
      if (meta) runs.push({ metaPath, meta });
    }
  }
  return runs;
}

/**
 * @description Default liveWorktreePaths producer: the set of harness worktree paths that still
 * exist on disk across every configured project (via the same listWorktrees producer the
 * holder-liveness scan uses). Decoupled from listWorktrees at the SEAM level (a test injects it
 * directly); the production wiring shares the producer so a run whose worktree is still live is
 * never mistaken for an orphan.
 * @param {object} producerOpts - threaded straight to listWorktreesFn.
 * @returns {Array<string>}
 */
function defaultLiveWorktreePaths(producerOpts) {
  return listWorktrees(producerOpts).map((entry) => entry.worktreePath);
}

/**
 * @description Builds the real prExists seam bound to the scoped gh: true iff an open OR merged
 * harness PR exists for the issue's head branch `harness/<issueNumber>`. Fail-closed (returns
 * false on any gh failure) so a dead holder with a PR is never wrongly relabeled back to ready.
 * @param {(args: string[]) => any} gh
 * @returns {(issueNumber: number) => boolean}
 */
function defaultPrExists(gh) {
  return (issueNumber) => {
    const prs = gh([
      "pr",
      "list",
      "--head",
      `harness/${issueNumber}`,
      "--state",
      "all",
      "--json",
      "number",
    ]);
    return Array.isArray(prs) && prs.length > 0;
  };
}

const PR_OPEN_FETCH_LIMIT = 100;
const REPO_NAME_TOKEN = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

/**
 * @description Builds a `project -> {owner, repo}` index ONCE from config.projects, backfilling
 * each entry from the fleet-level owner/repo at construction (entry.owner ?? config.owner,
 * entry.repo ?? config.repo). The legacy case (projects[] exists but lacks owner/repo) is
 * backfilled exactly once here. Entries with a malformed or non-string project name, owner, or repo
 * are skipped and therefore resolve to `null` at resolveRepoScope, letting the existing fail-closed
 * / fail-open behavior for an unknown project take over. An absent/empty projects[] leaves the
 * index empty; the caller falls back to the fleet-level owner/repo to preserve today's single-repo
 * behavior.
 *
 * Ambiguity rule: if the same project name appears more than once with DIFFERENT resolved
 * `{owner, repo}` coordinates, the name is removed from the index and never re-added, so it
 * resolves to `null` (fail-closed). Exact duplicates (same name, same owner, same repo) are
 * harmless and stay bound.
 * @param {object} config
 * @returns {Map<string, {owner: string, repo: string}>}
 */
function buildProjectRepoIndex(config) {
  const index = new Map();
  const ambiguous = new Set();
  if (Array.isArray(config.projects)) {
    for (const entry of config.projects) {
      const owner = entry.owner ?? config.owner;
      const repo = entry.repo ?? config.repo;
      if (
        typeof entry.project !== "string" ||
        typeof owner !== "string" ||
        !REPO_NAME_TOKEN.test(owner) ||
        typeof repo !== "string" ||
        !REPO_NAME_TOKEN.test(repo)
      ) {
        continue;
      }
      const name = entry.project;
      if (ambiguous.has(name)) continue;
      const existing = index.get(name);
      if (existing && (existing.owner !== owner || existing.repo !== repo)) {
        index.delete(name);
        ambiguous.add(name);
        console.warn(JSON.stringify({ op: "reaper.ambiguous-project", project: name }));
        continue;
      }
      index.set(name, { owner, repo });
    }
  }
  return index;
}

/**
 * @description Builds the real prOpen seam for the orphan-topic sweep: true iff the issue has an
 * OPEN PR (branch harness/<N> OR a body Closes/Fixes/Resolves/Refs #N link). DISTINCT from
 * defaultPrExists: open-STATE only (not open-OR-merged), no --head scoping (so a typed-branch PR
 * with a body-link is still recognized), and reuses pickSessionPr from cron-a-exit.mjs rather than
 * re-implementing the recognition regex.
 *
 * Uses a RAW spawn seam (spawnSync shape: {status, stdout, error}) — NOT the normalized gh/ghExec
 * seam — because the normalized seam returns [] on BOTH a gh error and a genuine empty result,
 * which are indistinguishable. On a gh outage that ambiguity would make every run look PR-less ->
 * the sweep would close every open PR's topic (the grave silence-regression). The raw seam exposes
 * status/error so we can FAIL OPEN: a gh error / non-zero status / unparseable stdout returns TRUE
 * (assume OPEN -> the sweep SKIPS, never closing a live topic under uncertainty). Only a SUCCEEDED
 * fetch with no matching PR returns false (close).
 *
 * MEMOIZED per owner/repo slug: one gh fetch per distinct repo per sweep, not one per
 * orphan-candidate run. The predicate is constructed once per runReaper call and closed over a
 * `Map<slug, cacheEntry>`. Receives a `resolveScope` function that returns `{owner, repo} | null`
 * for a project.
 * @param {(cmd: string, args: string[], opts: object) => {status: number, stdout: string, error?: *}} spawn
 * @param {(project: string) => {owner: string, repo: string} | null} resolveScope
 * @returns {(issueNumber: number, project?: string) => boolean}
 */
function makeDefaultPrOpen(spawn, resolveScope) {
  // Map keyed by owner/repo slug; both the gh-outage fail-open and the >= PR_OPEN_FETCH_LIMIT
  // fail-open are per slug so repo A's cached PR list never answers repo B's query (C3).
  const cache = new Map();
  return (issueNumber, project) => {
    const scope = resolveScope(project);
    if (!scope) return true; // unknown project -> fail OPEN (never close a topic under uncertainty)
    const slug = `${scope.owner}/${scope.repo}`;
    let cached = cache.get(slug);
    if (cached === undefined) {
      let res;
      try {
        res = spawn(
          "gh",
          [
            "pr",
            "list",
            "--repo",
            slug,
            "--state",
            "open",
            "--json",
            "number,headRefName,url,body",
            "--limit",
            String(PR_OPEN_FETCH_LIMIT),
          ],
          { encoding: "utf8" }
        );
      } catch {
        cached = { error: true };
      }
      if (cached === undefined) {
        if (!res || res.status !== 0 || res.error) cached = { error: true };
        else {
          try {
            cached = { prs: JSON.parse(res.stdout) };
          } catch {
            cached = { error: true };
          }
        }
      }
      cache.set(slug, cached);
    }
    // FAIL-OPEN: a gh outage -> assume OPEN -> the sweep SKIPS (never close a live topic under
    // uncertainty). Only a succeeded fetch with no matching PR returns false.
    if (cached.error) return true;
    const match = pickSessionPr(cached.prs, issueNumber);
    if (match !== null) return true;
    // Ambiguous full window: the repo has >= PR_OPEN_FETCH_LIMIT open PRs, so a genuinely-open
    // harness PR outside the fetched window is indistinguishable from "no match" — fail OPEN to
    // preservation (exactly like the gh-outage path above) so a still-OPEN PR's branch is never
    // deleted and cron-a-dispatch's local-ref resume probe never rebuilds from main, orphaning its
    // commits.
    if (Array.isArray(cached.prs) && cached.prs.length >= PR_OPEN_FETCH_LIMIT) return true;
    return false;
  };
}

/**
 * @description Builds the real issueClosed seam for the completed-worktree sweep: true iff the
 * issue's state is CLOSED, false iff OPEN, null on any gh failure or unparseable stdout. Uses the
 * RAW spawn seam (spawnSync shape {status, stdout, error}) — NOT the normalized gh/ghExec seam,
 * which returns [] on both a gh error and a genuine empty result. A gh outage must map to null
 * (unknown) so the prune fails closed, never to a false that could authorize a branch deletion.
 * issueClosed NEVER authorizes a branch deletion on its own — it only satisfies `concluded`.
 * @param {(cmd: string, args: string[], opts: object) => {status: number, stdout: string, error?: *}} spawn
 * @param {string} owner
 * @param {string} repo
 * @returns {(issueNumber: number) => boolean | null}
 */
export function makeDefaultIssueClosed(spawn, owner, repo) {
  return (issueNumber) => {
    let res;
    try {
      res = spawn(
        "gh",
        ["issue", "view", String(issueNumber), "--repo", `${owner}/${repo}`, "--json", "state"],
        { encoding: "utf8" }
      );
    } catch {
      return null;
    }
    if (!res || res.status !== 0 || res.error) return null;
    let parsed;
    try {
      parsed = JSON.parse(res.stdout);
    } catch {
      return null;
    }
    if (parsed && parsed.state === "CLOSED") return true;
    if (parsed && parsed.state === "OPEN") return false;
    return null;
  };
}

/**
 * @description Builds the real prMerged seam for the completed-worktree sweep: true iff a MERGED
 * PR exists for head branch harness/<issueNumber>, false iff none, null on any gh failure. Uses
 * the RAW spawn seam so a gh outage maps to null (unknown) — the LOAD-BEARING merged signal under
 * squash-merge (the merged branch is NOT an ancestor of main, so branchMerged is false for
 * legitimately merged work). prMerged===true alone satisfies both workPreserved and concluded.
 * @param {(cmd: string, args: string[], opts: object) => {status: number, stdout: string, error?: *}} spawn
 * @param {string} owner
 * @param {string} repo
 * @returns {(issueNumber: number) => boolean | null}
 */
export function makeDefaultPrMerged(spawn, owner, repo) {
  return (issueNumber) => {
    let res;
    try {
      res = spawn(
        "gh",
        [
          "pr",
          "list",
          "--repo",
          `${owner}/${repo}`,
          "--head",
          `harness/${issueNumber}`,
          "--state",
          "merged",
          "--json",
          "number",
        ],
        { encoding: "utf8" }
      );
    } catch {
      return null;
    }
    if (!res || res.status !== 0 || res.error) return null;
    let parsed;
    try {
      parsed = JSON.parse(res.stdout);
    } catch {
      return null;
    }
    return Array.isArray(parsed) && parsed.length > 0;
  };
}

/**
 * @description Builds the real branchMerged seam: `git -C <projectRoot> merge-base --is-ancestor
 * <branch> <defaultBranch>`. Exit 0 -> true (branch is an ancestor of the default branch), exit 1
 * -> false (not an ancestor), ANYTHING else (e.g. 128 for unrelated histories) -> null (unknown)
 * so the prune fails closed rather than reading an unrelated-history error as 'not an ancestor'. A
 * spawn throw also maps to null. NOT load-bearing under squash-merge (prMerged is the real merged
 * signal) — kept as a conservative extra workPreserved signal. The default branch is threaded from
 * config (default "main") so the probe stays live on fleets whose default branch is not main.
 * @param {(cmd: string, args: string[], opts: object) => {status: number, stdout: string, error?: *}} spawn
 * @param {string} [defaultBranch] - default "main"
 * @returns {(branch: string, projectRoot: string) => boolean | null}
 */
export function makeDefaultBranchMerged(spawn, defaultBranch = "main") {
  return (branch, projectRoot) => {
    if (!/^harness\/\d+$/.test(branch)) return null;
    let res;
    try {
      res = spawn(
        "git",
        ["-C", projectRoot, "merge-base", "--is-ancestor", branch, defaultBranch],
        { encoding: "utf8" }
      );
    } catch {
      return null;
    }
    if (!res || res.error) return null;
    if (res.status === 0) return true;
    if (res.status === 1) return false;
    return null;
  };
}

/**
 * @description Builds the real inspectWorktree seam: `git log --oneline <defaultBranch>..<branch>`
 * for the unmerged commits (workPreserved when length===0) and `git status --porcelain` for the
 * dirty/untracked inventory (recorded on the action descriptor). Returns EXACTLY
 * { unmergedCommits: string[], dirtyPaths: string[] } or null on any git failure — a wrong field
 * name or shape throws into reaper()'s per-worktree swallowing try/catch and silently never prunes
 * (fail closed). Both git calls run `-C <worktreePath>` so the status reflects THIS worktree. The
 * default branch is threaded from config (default "main") so the probe stays live on fleets whose
 * default branch is not main. A non-string stdout maps to null (unknown, fail-closed) — never to
 * an empty unmergedCommits that would authorize a branch delete.
 * @param {(cmd: string, args: string[], opts: object) => {status: number, stdout: string, error?: *}} spawn
 * @param {string} [defaultBranch] - default "main"
 * @returns {(worktree: { branch: string, worktreePath: string, projectRoot: string }) => { unmergedCommits: string[], dirtyPaths: string[] } | null}
 */
export function makeDefaultInspectWorktree(spawn, defaultBranch = "main") {
  const splitLines = (s) => (s ?? "").split("\n").filter((line) => line !== "");
  return (worktree) => {
    if (!/^harness\/\d+$/.test(worktree.branch)) return null;
    let logRes, statusRes;
    try {
      logRes = spawn(
        "git",
        ["-C", worktree.worktreePath, "log", "--oneline", `${defaultBranch}..${worktree.branch}`],
        { encoding: "utf8" }
      );
      statusRes = spawn(
        "git",
        ["-C", worktree.worktreePath, "status", "--porcelain"],
        { encoding: "utf8" }
      );
    } catch {
      return null;
    }
    if (!logRes || logRes.status !== 0 || logRes.error) return null;
    if (!statusRes || statusRes.status !== 0 || statusRes.error) return null;
    if (typeof logRes.stdout !== "string" || typeof statusRes.stdout !== "string") return null;
    return {
      unmergedCommits: splitLines(logRes.stdout),
      dirtyPaths: splitLines(statusRes.stdout),
    };
  };
}

/**
 * @description Best-effort default for removing a worktree, injected into the reaper logic as
 * opts.gitWorktreeRemove. Grown from the two-arg contract to accept an optional third { force }
 * argument: appends `--force` to `git worktree remove` ONLY when force is truthy. The existing
 * two-argument call sites (orphan/crash cleanup) pass no opts and stay unchanged — a dirty
 * worktree is deliberately left intact by a plain `git worktree remove` (#ac-1.3 preservation).
 * The safe completed-cleaned path passes { force: true }. The spawn seam is the 4th arg (defaulting
 * to the real spawnSync) so the REAL default can be driven by a fake spawn in tests.
 * @param {string} worktreePath
 * @param {string} projectRoot
 * @param {{ force?: boolean }} [opts]
 * @param {(cmd: string, args: string[], opts2: object) => any} [spawn]
 */
export function defaultGitWorktreeRemove(worktreePath, projectRoot, opts, spawn = spawnSync) {
  try {
    const argv = ["-C", projectRoot, "worktree", "remove"];
    if (opts && opts.force) argv.push("--force");
    argv.push("--", worktreePath);
    spawn("git", argv, { encoding: "utf8", stdio: "pipe" });
  } catch {
    // best-effort worktree remove
  }
}

/**
 * @description Best-effort default for deleting the orphan branch, injected into the reaper logic
 * as opts.gitBranchDelete. Runs `git -C <projectRoot> branch -D -- <branch>` with errors swallowed.
 * The spawn seam is the 3rd arg (defaulting to the real spawnSync) so the REAL default can be driven
 * by a fake spawn in tests — mirroring defaultGitWorktreeRemove so `git branch -D` no longer escapes
 * the injected spawn seam.
 * @param {string} branch
 * @param {string} projectRoot
 * @param {(cmd: string, args: string[], opts: object) => any} [spawn]
 */
export function defaultGitBranchDelete(branch, projectRoot, spawn = spawnSync) {
  try {
    spawn("git", ["-C", projectRoot, "branch", "-D", "--", branch], {
      encoding: "utf8",
      stdio: "pipe",
    });
  } catch {
    // best-effort branch delete
  }
}

export function runReaper(config, deps = {}) {
  const reaperFn = deps.reaper ?? reaper;
  const listWorktreesFn = deps.listWorktrees ?? listWorktrees;
  const runGitWorktreeList = deps.runGitWorktreeList ?? defaultRunGitWorktreeList;
  const readHolderFn = deps.readHolder ?? readHolder;
  const ghExec = deps.ghExec ?? defaultGhExec;
  const runLock = deps.runLock ?? runLockModule;
  const counter = deps.counter ?? counterModule;
  const tmuxHasSession = deps.tmuxHasSession ?? defaultTmuxHasSession;
  const tmuxKillSession = deps.tmuxKillSession ?? defaultTmuxKillSession;
  const now = deps.now ?? (() => Math.floor(Date.now() / 1000));
  const kill = deps.kill ?? process.kill;
  const readMetaFn = deps.readMeta ?? realReadMeta;
  const updateMetaFn = deps.updateMeta ?? realUpdateMeta;

  // Per-project owner/repo index. Backfills each entry from the fleet-level owner/repo at
  // construction (entry.owner ?? config.owner, entry.repo ?? config.repo). An absent/empty
  // projects[] falls back to the fleet-level owner/repo to preserve today's single-repo behavior.
  const repoIndex = buildProjectRepoIndex(config);
  const fleetRepo = { owner: config.owner, repo: config.repo };
  const hasDeclaredProjects = Array.isArray(config.projects) && config.projects.length > 0;
  function resolveRepoScope(project) {
    if (!hasDeclaredProjects) return fleetRepo;
    return repoIndex.get(project) ?? null;
  }

  // NORMALIZED gh seam (C4): prExists and the crash-recovery relabel `gh issue edit` go through
  // scopedGh, which appends `--repo owner/repo` at the end of the args array. The scope is resolved
  // from the project passed at call time. Unknown project fails closed with {ok:false} / false (C2).
  const ghByScope = new Map();
  function getScopedGh(project) {
    const scope = resolveRepoScope(project);
    if (!scope) return null;
    const slug = `${scope.owner}/${scope.repo}`;
    if (!ghByScope.has(slug)) {
      ghByScope.set(slug, scopedGh(scope.owner, scope.repo, ghExec));
    }
    return ghByScope.get(slug);
  }
  const gh =
    deps.gh ??
    ((args, project) => {
      const scoped = getScopedGh(project);
      if (!scoped) return { ok: false };
      return scoped(args);
    });
  const prExists =
    deps.prExists ??
    ((issueNumber, project) => {
      const scoped = getScopedGh(project);
      if (!scoped) return false;
      return defaultPrExists(scoped)(issueNumber);
    });

  // RAW spawn seam (spawnSync shape {status, stdout, error}) shared by the completed-sweep and
  // orphan-topic probes below. Used INSTEAD of the normalized gh/ghExec seam because that seam
  // returns [] on BOTH a gh error and a genuine empty result — an outage must map to null (unknown,
  // fail-closed prune), never to a false that would authorize a branch deletion.
  const spawn = deps.spawn ?? spawnSync;
  // Open-PR predicate for the orphan-topic sweep (F2). FAIL-OPEN on a gh outage, memoized per
  // distinct owner/repo slug, --state open + --json body + no --head so a typed-branch body-link
  // PR is still recognized. DISTINCT from prExists (open-OR-merged, --head harness/<N>).
  const prOpen = deps.prOpen ?? makeDefaultPrOpen(spawn, resolveRepoScope);

  // Completed-worktree sweep (behavior d) tri-state probes — all injectable, all fail closed
  // (null on any failure) so the pure-logic prune in reaper.mjs never deletes on uncertainty.
  // Each probe resolves `--repo owner/repo` from the per-project index at call time (C4).
  const issueClosedByScope = new Map();
  const issueClosed =
    deps.issueClosed ??
    ((issueNumber, project) => {
      const scope = resolveRepoScope(project);
      if (!scope) return null;
      const slug = `${scope.owner}/${scope.repo}`;
      if (!issueClosedByScope.has(slug)) {
        issueClosedByScope.set(slug, makeDefaultIssueClosed(spawn, scope.owner, scope.repo));
      }
      return issueClosedByScope.get(slug)(issueNumber);
    });
  const prMergedByScope = new Map();
  const prMerged =
    deps.prMerged ??
    ((issueNumber, project) => {
      const scope = resolveRepoScope(project);
      if (!scope) return null;
      const slug = `${scope.owner}/${scope.repo}`;
      if (!prMergedByScope.has(slug)) {
        prMergedByScope.set(slug, makeDefaultPrMerged(spawn, scope.owner, scope.repo));
      }
      return prMergedByScope.get(slug)(issueNumber);
    });
  const branchMerged =
    deps.branchMerged ?? makeDefaultBranchMerged(spawn, config.defaultBranch ?? "main");
  const inspectWorktree =
    deps.inspectWorktree ?? makeDefaultInspectWorktree(spawn, config.defaultBranch ?? "main");
  // Force-aware worktree remove: the safe completed-cleaned path passes { force: true }; the
  // orphan/crash paths pass no opts (two-arg contract unchanged). Bound to the raw spawn seam so a
  // fake spawn can drive the REAL default in tests.
  const gitWorktreeRemove =
    deps.gitWorktreeRemove ??
    ((worktreePath, projectRoot, opts) => defaultGitWorktreeRemove(worktreePath, projectRoot, opts, spawn));
  // Best-effort branch delete, bound to the raw spawn seam so a fake spawn observes the branch
  // deletion too (mirrors gitWorktreeRemove). Without this, `git branch -D` falls through to
  // reaper.mjs's own default and bypasses deps.spawn.
  const gitBranchDelete =
    deps.gitBranchDelete ??
    ((branch, projectRoot) => defaultGitBranchDelete(branch, projectRoot, spawn));

  // The zero-arg listWorktrees seam handed to the reaper logic: delegates to the injected producer
  // over config.projects (every project the shared cron sweeps in one invocation), bound to the
  // real git-worktree-list and readHolder seams (or their injected fakes).
  const listWorktreesSeam = () =>
    listWorktreesFn({
      projects: config.projects,
      runGitWorktreeList,
      readHolder: readHolderFn,
    });

  // Best-effort notifier: injected (tests observe) or no-op default. The real notifier + drain live
  // in mainReaper. Each notification's `<project>` prefix comes from the per-worktree action entry
  // (the reaper is a shared cron over many projects), never a single fleet value.
  const notify = deps.notify ?? (() => {});

  // Orphan topic-close seams (task-9). listObsRuns/liveWorktreePaths default to real fs/git
  // enumeration over config.projects; closeForumTopic is the token-bound seam mainReaper builds
  // (the token is resolved there via makeNotifier reading ~/.claude/.dev.vars — never the session
  // env). When closeForumTopic is NOT injected (e.g. a run-crons test that only exercises the
  // worktree scan), sweepOrphanTopics no-ops.
  const listObsRunsSeam = deps.listObsRuns ?? (() => defaultListObsRuns(config.projects, readMetaFn));
  const liveWorktreePathsSeam =
    deps.liveWorktreePaths ?? (() => defaultLiveWorktreePaths({
      projects: config.projects,
      runGitWorktreeList,
      readHolder: readHolderFn,
    }));
  const closeForumTopicFn = deps.closeForumTopic ?? null;
  const updateMetaSeam = deps.updateMeta ?? updateMetaFn;

  const result = reaperFn({
    listWorktrees: listWorktreesSeam,
    tmuxHasSession,
    kill,
    now,
    prExists,
    gh,
    runLock,
    counter,
    tmuxKillSession,
    listObsRuns: listObsRunsSeam,
    liveWorktreePaths: liveWorktreePathsSeam,
    closeForumTopic: closeForumTopicFn,
    updateMeta: closeForumTopicFn ? updateMetaSeam : undefined,
    prOpen,
    issueClosed,
    prMerged,
    branchMerged,
    inspectWorktree,
    gitWorktreeRemove,
    gitBranchDelete,
  });

  // reaper returns the actions array with a `topicCloses` property attached; a fake/injected
  // reaper may return undefined or a bare array (backward compatible with the existing tests).
  const actions = Array.isArray(result) ? result : (result?.actions ?? []);
  const topicCloses = (result && result.topicCloses) || (result?.actions?.topicCloses) || [];

  const ACTION_TYPE = {
    "watchdog-killed": "reaper-killed",
    "crash-recovered": "reaper-recovered",
    "orphan-cleaned": "reaper-orphan-cleaned",
    "completed-cleaned": "reaper-orphan-cleaned",
  };
  for (const a of actions) {
    try {
      const type = ACTION_TYPE[a.action];
      if (type) notify({ type, project: a.project, issue: a.issueNumber });
    } catch {
      // fail-open — a notify failure never blocks the sweep
    }
  }

  // Return the orphan close promises so mainReaper can await them before the process exits.
  return topicCloses;
}

/**
 * @description CLI wrapper: builds the real FLEET-level notifier, runs runReaper with it injected,
 * and awaits drain() — AND the orphan topic-close promises — before the shared reaper process
 * exits so its notifications and topic closes are not dropped. The closeForumTopic token is
 * resolved HERE via makeNotifier(config,{homeDir}) reading ~/.claude/.dev.vars at runtime (mirrors
 * the task-4 token judgment) — never from the session env-file or a threaded secret. When notify is
 * unconfigured the token-bound closeForumTopic resolves to a no-op { ok:false } so the orphan sweep
 * still records status:'closed' on disk (the close is best-effort, fail-open).
 * @param {object} config
 * @returns {Promise<void>}
 */
export async function mainReaper(config) {
  const notifier = makeNotifier(config, { homeDir: config.homeDir });
  // Token-bound closeForumTopic: the token lives on notifier.config (resolved from ~/.claude/.dev.vars).
  // Bound here so the reaper logic never resolves the token itself; it only receives this seam.
  const closeForumTopic = notifier.config
    ? (input) => realCloseForumTopic(input, {
        config: notifier.config,
        fetch: config.fetch,
        log: config.log,
        timeoutMs: config.timeoutMs,
      })
    : async () => ({ ok: false });

  let topicCloses = [];
  try {
    topicCloses = runReaper(config, { notify: notifier.notify, closeForumTopic }) ?? [];
  } finally {
    try {
      await Promise.allSettled(topicCloses);
    } catch {
      // fail-open: a close failure never blocks the reaper exit
    }
    try {
      await notifier.drain();
    } catch {
      // fail-open
    }
  }
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const arg = process.argv[2];
  const configPath = arg === "--config" ? process.argv[3] : arg;
  mainReaper(loadConfig(configPath)).catch((err) => {
    console.error(`run-reaper: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  });
}